### ISSUE TITLE
ContentMine logo is out of date

### ISSUE THREAD

**Issue by ghost** [ContentMine/meta#10]
@tarrow noted today that the ContentMine logo used for ContentMine repositories on GitHub is out of date, and kindly offered to fix this.

**Comment by tarrow** [comment]
done but still seems to be cached many hours later
Will look up again tomorrow to see if done.

**Comment by ghost** [comment]
Thanks @tarrow !

Works for me, so will close this. Please re-open if issue persists.
